# Generated by Django 2.0 on 2017-12-19 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('targer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPlanned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planned', models.DateField()),
                ('date_achievied', models.DateField()),
                ('nb_activities', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BestApp.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='GanttTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('duration', models.DurationField()),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(default='OUTPUT', max_length=10)),
                ('category', models.CharField(default='DONORS', max_length=10)),
                ('unit', models.CharField(default='Number', max_length=10)),
                ('target', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MainOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BestApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BestApp.Output'),
        ),
    ]
