# Generated by Django 2.0 on 2017-12-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestApp', '0002_auto_20171219_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityplanned',
            old_name='nb_activities',
            new_name='nb_achieved',
        ),
        migrations.AddField(
            model_name='activityplanned',
            name='nb_planned',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
