# Generated by Django 2.0 on 2017-12-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestApp', '0004_auto_20171219_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityplanned',
            name='date_achievied',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='activityplanned',
            name='date_planned',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='activityplanned',
            name='nb_achieved',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='activityplanned',
            name='nb_planned',
            field=models.IntegerField(blank=True),
        ),
    ]
