# Generated by Django 2.0 on 2017-12-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestApp', '0005_auto_20171219_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityplanned',
            old_name='date_achievied',
            new_name='date_achieved',
        ),
    ]
